### ISSUE TITLE
Feature Information

### ISSUE THREAD

**Issue by khaledb9** [dgehringer/sqsgenerator#37]
Hello. 

First I would like to really thank you for this tool. The problem of Sqs generation is very time consuming and you have made it work on parallel machines. 

I have a question about the parallel implementation: I cannot initialize the mpi runtime for the tool. I was able to specify the threads_per_rank for instance as [8,8,8 ...] 16 times then I run mpirun -n 16. I get the message that the mpi runtime was not initialized and even though the program does it and continues but I would like to be able to know how to do it to be able to calculate the estimated time etc. 

Also, is there is anyway to output the structures during the mpirun? I would like to be able to see how the objective function changes for instance. Sometimes the difference in objective function is very small but it takes numerous iterations to reach to it. I realize the log level can be changed, but the program will basically stop giving any kind of output when the iterations start until it is done with the number of iterations.

Thank you. 
Khaled.

**Comment by dgehringer** [comment]
Dear @khaledb9!

Just a simple question before! Did you obtain your binary via conda or, did you compile the package yourself?
The reason why I am asking is because the conda binary only exhibits OpenMP parallelization. For MPI one needs to compile the package manually. It is a little bit hidden in the [documentation](https://sqsgenerator.readthedocs.io/en/latest/installation_guide.html#with-conda). Let me know if you need support.

*...but I would like to be able to know how to do it to be able to calculate the estimated time etc*
There I do suggest to make an estimate without MPI and multiply in simply. The reason is that communication overhead is negligible and you can safely extrapolate. 

*Also, is there is anyway to output the structures during the `mpirun`? I would like to be able to see how the objective function changes for instance.*

Not directly, but hence the binary needs to be compiled anyway for MPI support it would be easy to add a line line in [sqs.cpp](https://github.com/dgehringer/sqsgenerator/blob/cf79d647d732a3467d3132cc4dbb8001e0bbedd9/sqsgenerator/core/src/sqs.cpp#L340), that prints the current time and value of the objective function.

I hope that helps and best regards

**Comment by khaledb9** [comment]
Thank you for your response. 

I compiled it myself and the version supports mpi. But I was not able to overcome that mpi runtime initialized message even though the program assigns the ranks and threads as desired. 

Could you please point me to the block of code to modify for the output in Sqs.cpp ? 

Thank you

**Comment by dgehringer** [comment]
Hi @khaledb9 

Does `sqsgenerator --version` contain a line stating `features: ['openmp', 'mpi']`? The reason why I'm asking is that the build will continue if `SQS_USE_MPI` is set to `ON` but the MPI library was not found, then it silently turns off MPI again.

*Could you please point me to the block of code to modify for the output in Sqs.cpp ?*
Of course, I personlly would put it there in [sqs.cpp](https://github.com/dgehringer/sqsgenerator/blob/cf79d647d732a3467d3132cc4dbb8001e0bbedd9/sqsgenerator/core/src/sqs.cpp#L359C21-L359C21 ). I'd provide you with patch file anyway, once we are sure that everything worked out with the build system correctly

**Comment by khaledb9** [comment]
Hello 

Yes it includes mpi in the --version command. 
When I Run "mpirun -np 16 Sqsgen run iteration" for instance, the stdout file says "could not initialize mpi runtime, i will do it !" And it assigns the correct ranks. 

I set the threads_per_rank input parameter to [8, 8, 8] etc assuming I'm using 3 ranks and 8 threads.

The idea why I'm asking about output the best function, I found out via a simple modification in 354 where i added a print statement to the global_best_function. That it takes much fewer iterations to reach the objective for some systems, more than the provided number of iterations. I think a very useful addition to the code would be to check if the function reached zero before the iterations end and jump to the output phase. 

Thank you

**Comment by dgehringer** [comment]
Dear @khaledb9!

Ok, many thanks for your informations! Can you run the code with MPI debug, to further investigate what is going on? E.g. for Intel MPI (I_MPI_DEBUG). Actually if the `MPI_Init` function returns zero, it is hard to fix in the code, since the code just calls the MPI library.


*I think a very useful addition to the code would be to check if the function reached zero before the iterations end and jump to the output phase.*

When you interupt the program (Crtl+C) it will write the results of the current optimizations. The point is however, there are cases, when one is not interested only in a single SQS but multiple structures. With our approach there is not a single structure which might mimize the objective function, but there may be many of them. So there may be several best  structures. Secondly, because of the finite number of cells, the minimal value the objective function can approach a non-zero values, but this depends on the user settings such as the shell weights. So it is hard to tell a-priori when the  minimzation has reached the optimal value.

*I found out via a simple modification in line 354 of Sqs.cpp where i added a print statement to the global_best_function*

Indeed, there is nothing more than a print statement to add. However, L354 is the MPI synchronization logic, so whether you see this print statement depends on whether a different rank has found something, which is ensured to be done by a single thread at a time. After that the thread populates the value to it's thread team members. The point where you can be sure that results a synchronized across both MPI ranks and OpenMP threads is L369. So therefore, I suggest to 
add there something like

```C++
// You want only one thread per MPI rank to print the message, since they all see the same value
// Warning makes sure you see it, without changing the verbosity level
#pragma omp single
BOOST_LOG_TRIVIAL(warning) << "MPI rank: " << mpi_rank << ", current best objective" << best_objective;
```

**Comment by khaledb9** [comment]
Thank you for your response.

I will try the mpi debug and let you know the outcome.

Regarding the output, I realize that Ctrl+C will write an output but it will terminate the program. My idea is that as the program generates new structures based on the current objective functions. I would like to be able to take the structure and test it outside in Dft for instance.

Consider the following scenario to explain my situation:
Assuming that the best possible objective function is 0.1 and after several hours 0.2 was obtained. Now if it takes double the time to reach to 0.1, it is worth it to try the structure obtained from (0.2) as most probably the difference in energy won’t be large, it would be a good representation and save many computation hours. To be able to do that I have to get the structure while the iterations are still running.

Is there is a way for instance to call an output function after every generation of a new objective function.

 I have to admit that my c++ knowledge doesn’t extend as far as MPI implementation but I have been trying to study your code for such implementation of output. If you kindly can point me to a way to call the output function after printing the objective function. My guess is that the I/O operation will increase the computation time, however if you have other ideas kindly let me know.

Regards


On 10 Jul 2023, at 5:47 PM, dgehringer ***@***.***> wrote:

﻿

Dear @khaledb9<https://github.com/khaledb9>!

Ok, many thanks for your informations! Can you run the code with MPI debug, to further investigate what is going on? E.g. for Intel MPI (I_MPI_DEBUG). Actually if the MPI_Init function returns zero, it is hard to fix in the code, since the code just calls the MPI library.

I think a very useful addition to the code would be to check if the function reached zero before the iterations end and jump to the output phase.

When you interupt the program (Crtl+C) it will write the results of the current optimizations. The point is however, there are cases, when one is not interested only in a single SQS but multiple structures. With our approach there is not a single structure which might mimize the objective function, but there may be many of them. So there may be several best structures. Secondly, because of the finite number of cells, the minimal value the objective function can approach a non-zero values, but this depends on the user settings such as the shell weights. So it is hard to tell a-priori when the minimzation has reached the optimal value.

I found out via a simple modification in line 354 of Sqs.cpp where i added a print statement to the global_best_function

Indeed, there is nothing more than a print statement to add. However, L354 is the MPI synchronization logic, so whether you see this print statement depends on whether a different rank has found something, which is ensured to be done by a single thread at a time. After that the thread populates the value to it's thread team members. The point where you can be sure that results a synchronized across both MPI ranks and OpenMP threads is L369. So therefore, I suggest to
add there something like

// You want only one thread per MPI rank to print the message, since they all see the same value
// Warning makes sure you see it, without changing the verbosity level
#pragma omp single
BOOST_LOG_TRIVIAL(warning) << "MPI rank: " << mpi_rank << ", current best objective" << best_objective;

**Comment by dgehringer** [comment]
Dear @khaledb9!

*Assuming that the best possible objective function is 0.1 and after several hours 0.2 was obtained. Now if it takes double the time to reach to 0.1, it is worth it to try the structure obtained from (0.2) as most probably the difference in energy won’t be large, it would be a good representation and save many computation hours. To be able to do that I have to get the structure while the iterations are still running.*

I do exactly see your point, and moreover think that I do understand what you mean. The point is however, as the structure is randomly generated, the probability to find the best one is the same of each structure. In other words, where is no such concept, of "*resuming*" and optimization. If you do a second run with and end up with a lower objective function, then it is because you sampled twice as many structures. But as the events (the structure generation) are independent of each other, it does not matter if you do one run with $2\cdot10^6$ iterations, or two smaller ones with $10^6$ iterations each.

*I would like to be able to take the structure and test it outside in Dft for instance*

Actually we thought about this, namely to allow the user to pass callback functions (e.g. new objective found), the point is just that integration  is not so easy. But that is something we can do. We have just to agree what to expose

**Comment by khaledb9** [comment]
Thank you for the clarification. I did some test runs and eventually on enough cores it takes less than 24hours to reach a non-changing objective function to consider testing the structure and hence interrupting the program is the correct way.

Indeed the dft coupling is an excellent step but I do realize the time and effort required to do that. However, the tool is remarkable in terms of the performance.

Regarding the MPI issue. I’m not using intel, I use openmpi. The program build supports mpi. I installed it on the conda environment to avoid any confusion with the hpc versions. I run normal using “mpirun -n XX sqsgen ..” and specify the threads per rank: [2,2,2,…] XX times. However, the program says the same message of “Mpi runtime is not initialized, I’m going to do that !”. Anyway it assigns the correct XX number of ranks and correct number of threads.

Sent from my iPhone

On 12 Jul 2023, at 11:53 AM, dgehringer ***@***.***> wrote:

﻿

Dear @khaledb9<https://github.com/khaledb9>!

Assuming that the best possible objective function is 0.1 and after several hours 0.2 was obtained. Now if it takes double the time to reach to 0.1, it is worth it to try the structure obtained from (0.2) as most probably the difference in energy won’t be large, it would be a good representation and save many computation hours. To be able to do that I have to get the structure while the iterations are still running.

I do exactly see your point, and moreover think that I do understand what you mean. The point is however, as the structure is randomly generated, the probability to find the best one is the same of each structure. In other words, where is no such concept, of "resuming" and optimization. If you do a second run with and end up with a lower objective function, then it is because you sampled twice as many structures. But as the events (the structure generation) are independent of each other, it does not matter if you do one run with $2\cdot10^6$ iterations, or two smaller ones with $10^6$ iterations each.

I would like to be able to take the structure and test it outside in Dft for instance

Actually we thought about this, namely to allow the user to pass callback functions (e.g. new objective found), the point is just that integration is not so easy. But that is something we can do. We have just to agree what to expose

**Comment by dgehringer** [comment]
Dear @khaledb9!

This message is no error message, but rather an information only. The programm outputs it [in this line](https://github.com/dgehringer/sqsgenerator/blob/master/sqsgenerator/core/src/sqs.cpp#L195). The reason for this message is, that commonly, python programs are MPI paralellized with `mpi4py`, however, that would impose an additional dependency. Therefore if `sqsgenerator` is not encapusulated in an `mpi4py` (which would do the MPI runtime initialization) script we have to do it ourselves. You just get an info then

I hope that does clarify your issue

**Comment by dgehringer** [comment]
Hi @khaledb9!

There is a new feature in version *0.3* of the program, which now allows to pass a function, that will be called when a certain condition is met. The feature is still undocumented

there are two callbacks
 -  `better_or_equal`: is triggered when a structure with equal or lower objective is found
 - `better`: is triggered when a configuration with lower objective is found

An example would look like this:

```python

from typing import *
from sqsgenerator.public import SQSResult, Structure, sqs_optimize


def callback(iteration: int, structure: Structure, result: SQSResult, mpi_rank: int, thread_id: int) -> Optional[bool]:
    # do what ever you want here
   # but since you run MPI you want to execute callbacks only on the "HEAD" rank
   if mpi_rank == 0:
       # call DFT code
       # or anything else you want
       stop = True
       return stop

settings.update(
    callbacks=dict(
        better=[callback]  # trigger only if a better configuration was found
   )
)

result, timings = sqs_optimize(settings, pass_structure=True)
```

The return value of the callback is important. So `None` or `False` will be ignored. If `True`  or an value that evaluates to `True` returned it will instruct *sqsgenerator* to stop the main optimization loop.

I think with that feature you are now able to track the progress of the optimization!
Let me know if it is fine know :smile:, and we can close the Issue
